import "server-only";
import dataset from "@/data/service-centres.json";
import { createCentreSearch, toCentres } from "@/lib/service-centres";

// Generated by `npm run update:centres` from the official SPARSH locator.
const centres = toCentres(dataset.centres);

export const centreDirectory = {
  source: dataset.source,
  retrievedAt: dataset.retrievedAt,
  total: centres.length,
  search: createCentreSearch(centres),
};
